### PR TITLE
Dependencies in README should have test scope by default

### PR DESCRIPTION
**Pull request by michalvavrik**
https://github.com/quarkiverse/quarkus-pact/issues/28 is fix and LATEST (that is 1.0.0.Final) already contains fixed as it is based on 3.0.1.Final.

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @holly-cummins

**Comment by holly-cummins** [comment]
Good spot, @michalvavrik, thanks!

**Comment by holly-cummins** [comment]
@all-contributors please add @michalvavrik

**Comment by holly-cummins** [comment]
https://github.com/all-contributors please add @michalvavrik for doc

**Comment by holly-cummins** [comment]
@all-contributors please add @michalvavrik for doc

**Pull request merged**
