### PR TITLE
Adjust doc title

### PR DESCRIPTION
**Pull request by gastaldi**
This will remove the  `Quarkus ` prefix in the documentation title

### CODE REVIEW

**Comment by holly-cummins** [comment]
Oh dear, the build is a bit of a mess with this 

```
plugin:3.2.0.Final:build: java.lang.NoSuchMethodError: 'void io.quarkus.bootstrap.app.AugmentResult.<init>(java.util.List, io.quarkus.bootstrap.app.JarResult, java.nio.file.Path)'
```

**Comment by gastaldi** [comment]
But it isn't related to this change, is it?

**Comment by holly-cummins** [comment]
The last build was green, and the failure is in the docs build. I'll try and request a vanilla build to be sure.

**Comment by holly-cummins** [comment]
Hm, strange. https://github.com/quarkiverse/quarkus-pact/actions/runs/5213826849 doesn't have this change, and it fails in the same way. So the change is off the hook (phew!). 

... but why has the docs build spontaneously started failing?

**Comment by gastaldi** [comment]
I guess the real question is: Why is it failing with 3.2.0.Final if https://github.com/quarkiverse/quarkus-pact/pull/133 wasn't merged yet?

**Comment by gastaldi** [comment]
- Fixed in https://github.com/quarkiverse/quarkus-pact/pull/135

**Pull request merged**
